### ISSUE TITLE
Period only 4 hours

### ISSUE THREAD

**Issue by Johannes3** [poralix/load_monitor#1]
The periode field accept only the current 4 hours periode.   If setting a past periode, it jumps back to the current set.

**Comment by Johannes3** [comment]
The server load details are missing.  If I move the mouse over a peak from the graph, I can click to come to the details site, and this is empty, there are no values.  (screenshot attached)
![server load details empty](https://user-images.githubusercontent.com/11931116/39330285-6a2cb638-49a1-11e8-9b41-a71ef5430170.jpg)

**Comment by poralix** [comment]
Hello,

Thanks for your report. It was already fixed in the latest version.

Regards,
Alex.
