### ISSUE TITLE
PHP 7.4 results in not plugin taking a load time to load

### ISSUE THREAD

**Issue by jcastilloalonso** [poralix/load_monitor#2]
Hello Poralix,

Thanks for keeping up this plugin updated.

Since upgrading to PHP 7.4 I've been unable to make it work, it stays loading indefinitely.

Any ideas what might be the problem?

Thanks!

**Comment by jcastilloalonso** [comment]
After leaving it loading for over 5 minutes, the plugin loaded. Not an issue sorry

**Comment by jcastilloalonso** [comment]
Hey Poralix, reopening the issue as I've been checking and plugin usually takes a long time to load since updating to PHP 7.4. Is there any way to troubleshoot why this is taking so long?

**Comment by gralex54** [comment]
Hello,

If a plugin is loading too slow, then you might change the following settings:

- Maximum days to remember loads: default 91 - **set it to 30-45**
- Save interval in minutes: default 1 - **set to 2-3**

This will result in smaller database, and I hope in faster loading.
